services:
  env:
    image: docker.io/slaskis/ace-example:latest
    build: .
    restart: no
    secrets:
      - env
      - identity

secrets:
  env:
    file: ./.env.ace
  identity:
    file: ./identity
