---
apiVersion: v1
data:
  identity: IyBjcmVhdGVkOiAyMDI0LTA0LTA3VDEyOjMwOjIxKzAyOjAwCiMgcHVibGljIGtleTogYWdlMWN0ZTgzNGF1cGE1dzh3enEwMzlwemo5eDIweHduZmVrMzR2aDRyYWo1Mzl6azBlc2d5bnNyd3N3NmgKQUdFLVNFQ1JFVC1LRVktMU5QTkZFU1pTRDVEU1FDS0NZS1EzVzBUOEpOVVc3Q1hKNEE0MjRBRkxLRENRSEpSNlhHOVM3NFNBTTMK
kind: Secret
metadata:
  labels:
    io.kompose.service: identity
  name: identity
type: Opaque

---
apiVersion: v1
data:
  env: IyBhY2UvdjE6TUZUV0tMTEZOWlJYRTZMUU9SVVc2M1JPTjVaR09MM1dHRUZDMlBSQUxBWkRLTkpSSEVRRkVNU1hOWTJFSTZERU1GS0hJUVRJT0ZERlVUMk9PNVVXQ05UTE5OSUhRNFNFTEE0RUtSMkdNWlVVV1FLV05GSVRDVjJWQkpNVkc0MllPTkxFMlVMV0tOMkVXUkxCRk4zSFMyQ1dPNDNUT04yVktGRkZHNktUTTVMSEFXQ0pNSVlXUVpURU1ONEVVUklLRlVXUzJJRFROQlNVT1MzV0pKRVdXNlNOSEJNVVVVQ0dOWkFYSVJCU09OQ0ZRMkpWTjVVSEVaSlVOWTNVQzMzRFBKSlZFNURFUEJaUVZXQjc2UzNPWUE1RTJQUlBNQVhZV1ZHUExUNkJUV1ZWTVNUNEFOSUZaQVFMUFJNRUNHWDNVS1pHWVZSSjRGTUU1TUxZT0VIWUFDVlJMUUQ3NTdYTkhSNlVNWlhNU1lKTEM0S0tMQ1pRPT09PQpIRUxMTz0zUlU2WEJISkdJNE5CMlpKNkNRR1FYNkhKU1pGQkhFSE9VT0JKRldLUFNHQjROUDYyMkc0RTVOREFPRDVHNVVZN0ZUTUpSUT0KCg==
kind: Secret
metadata:
  labels:
    io.kompose.service: env
  name: env
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/docker-default: "true"
    io.kompose.service: env
  name: env
spec:
  containers:
    - image: docker.io/slaskis/ace-example:latest
      name: env
      volumeMounts:
        - mountPath: /run/secrets/env
          subPath: env
          name: env
        - mountPath: /run/secrets/identity
          subPath: identity
          name: identity
  restartPolicy: Never
  volumes:
    - name: env
      secret:
        items:
          - key: env
            path: env
        secretName: env
    - name: identity
      secret:
        items:
          - key: identity
            path: identity
        secretName: identity
