name: Go

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o ace-${{ matrix.goos }}-${{ matrix.arch }} -v ./...

      - name: Upload
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: "ace-${{ matrix.goos }}-${{ matrix.arch }}",
              data: fs.readFileSync("ace-${{ matrix.goos }}-${{ matrix.arch }}")
            })
