name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -v -cover -ldflags '-s -w -X main.version=test' -o ace-${{ matrix.goos }}-${{ matrix.arch }} .
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
      - run: go test -v -race .
        env:
          ACE_TESTBIN: ./ace-${{ matrix.goos }}-${{ matrix.arch }}
